services:
  mysql_dev:
    image: mysql:5.7
    container_name: mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: study_board
      TZ: Asia/Seoul
    networks:
      - my_network_dev
    ports:
      - "3306:3306"

  centos_dev:
    build: ./ph
    container_name: centos_dev
    depends_on:
      - mysql_dev
    networks:
      - my_network_dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ph:/app
    command: /bin/sh -c "/usr/sbin/httpd -D FOREGROUND && mkdir -p /run/php-fpm && chown apache:apache /run/php-fpm && php-fpm -D"

  node_dev:
    build: ./node
    container_name: node_dev
    depends_on:
      - mysql_dev
    networks:
      - my_network_dev
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
      # - /app/node_modules

networks:
  my_network_dev:
    driver: bridge
